[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vpnkitrc = { path = ".." }
ntex = { version = "0.7.2", features = ["tokio"] }
